# Generated by Django 2.2.7 on 2021-02-27 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import setup.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs.')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.CharField(db_index=True, max_length=50)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('logo', models.ImageField(blank=True, help_text='logo size must be 100 x 100 px', null=True, upload_to=setup.validators.agent_logo, validators=[setup.validators.validate_max_image_size], verbose_name='Agent Logo')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_created', to=settings.AUTH_USER_MODEL)),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Agent',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('dob', models.DateField(max_length=10, verbose_name='Date of Birth')),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expire_date', models.DateField(max_length=10)),
                ('visa_number', models.CharField(max_length=50)),
                ('visa_expire_date', models.DateField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('upload_passport', models.ImageField(help_text='upload your passport here', upload_to=setup.validators.upload_passport, validators=[setup.validators.validate_max_image_size])),
                ('upload_visa', models.ImageField(help_text='upload your visa here', upload_to=setup.validators.upload_visa, validators=[setup.validators.validate_max_image_size])),
                ('picture', models.ImageField(blank=True, help_text='logo size must be 100 x 100 px', null=True, upload_to=setup.validators.customer_image, validators=[setup.validators.validate_max_image_size], verbose_name='Profile Picture')),
                ('status', models.CharField(choices=[('posted', 'posted'), ('approved', 'approved'), ('delivered', 'delivered')], default='posted', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Agent', verbose_name='Agent Name')),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_created', to=settings.AUTH_USER_MODEL)),
                ('updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Customer',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
