# Generated by Django 2.2.7 on 2021-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20210227_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
