# Generated by Django 2.2.7 on 2021-03-06 10:49

from django.db import migrations, models
import setup.validators


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_agentuser_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_expire_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_passport',
            field=models.ImageField(blank=True, help_text='upload your passport here', null=True, upload_to=setup.validators.upload_passport, validators=[setup.validators.validate_max_image_size]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upload_visa',
            field=models.ImageField(blank=True, help_text='upload your visa here', null=True, upload_to=setup.validators.upload_visa, validators=[setup.validators.validate_max_image_size]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='visa_expire_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='visa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
